<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>

		<!-- exe 图标 -->
		<ApplicationIcon>icon.ico</ApplicationIcon>

		<!-- 单文件发布（框架依赖，不自包含） -->
		<PublishSingleFile>true</PublishSingleFile>
		<SelfContained>false</SelfContained>
		<IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>

		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
	</PropertyGroup>

	<!-- 包含字体文件 -->
	<ItemGroup>
		<Resource Include="SlexionWindowButtons.ttf" />
		<Content Include="icon.ico">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

</Project>
